import 'package:wiki_app/model/WikiModel.dart';

class Autogenerated {
  String _batchcomplete;
  Query _query;

  Autogenerated({String batchcomplete, Query query}) {
    this._batchcomplete = batchcomplete;
    this._query = query;
  }

  String get batchcomplete => _batchcomplete;
  set batchcomplete(String batchcomplete) => _batchcomplete = batchcomplete;
  Query get query => _query;
  set query(Query query) => _query = query;

  Autogenerated.fromJson(Map<String, dynamic> json) {
    _batchcomplete = json['batchcomplete'];
    _query = json['query'] != null ? new Query.fromJson(json['query']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['batchcomplete'] = this._batchcomplete;
    if (this._query != null) {
      data['query'] = this._query.toJson();
    }
    return data;
  }
}

class Query {
  Pages _pages;

  Query({Pages pages}) {
    this._pages = pages;
  }

  Pages get pages => _pages;
  set pages(Pages pages) => _pages = pages;

  Query.fromJson(Map<String, dynamic> json) {
    _pages = json['pages'] != null ? new Pages.fromJson(json['pages']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._pages != null) {
      data['pages'] = this._pages.toJson();
    }
    return data;
  }
}
